# Parameters for the example pipeline. Feel free to delete these once you
# remove the example pipeline from pipeline.py and the example nodes in
# nodes/example.py
example_test_data_ratio: 0.2
example_num_train_iter: 10000
example_learning_rate: 0.01
supported_currencies_list:
  - BNB
  - BTC
  - ETH
  - XRP
  - USDT
raw_folder: "data/01_raw"
needed_obj_keys:
  s: name
  a: best_ask_price
  A: best_ask_quantity
  b: best_bid_price
  B: best_bid_quantity
  E: time
  n: trades_count
